name: Mirco_test
favicon: null
layout_spectrum: 0.50707
typography_spectrum: 0.7431
title: Mircosoft
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#f0f217'
    - '#2e8f92'
    - '#bebebf'
  brandStrength: 1
  lightness: 1
  saturation: 0.875
  rhythmicContrast: 0.25
purpose: []
