name: Mirco_test
favicon: null
layout_spectrum: 0.25066
typography_spectrum: 0.7431
title: Miroslav Novotný
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#f0f217'
    - '#2e8f92'
    - '#bebebf'
  brandStrength: 0.0625
  lightness: 0
  saturation: 1
  rhythmicContrast: 1
purpose: []
