name: Mirco_test
favicon: null
layout_spectrum: 0.25066
typography_spectrum: 0.7431
title: Mircosoft
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#dfddb6'
    - '#aebc43'
    - '#62624a'
    - '#121210'
    - '#f1ee0e'
  brandStrength: 1
  lightness: 0.3125
  saturation: 0.875
  rhythmicContrast: 0
purpose: []
